msm_serial_hs: Include sched types header
This fixes the following compilation error:

../drivers/tty/serial/msm_serial_hs.c:2752:21: error: variable has incomplete type 'struct sched_param'
        struct sched_param param = { .sched_priority = 1 };
                           ^
../include/linux/sched.h:52:8: note: forward declaration of 'struct sched_param'
struct sched_param;
       ^

Fixes: a1ce6139355 ("msm_serial_hs: Make thread RT to improve Bluetooth performance")
Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>
Signed-off-by: NotZeetaa <rodrigo2005contente@gmail.com>